version: '3.4'

services:
  ndtnfhomework004migratetotypescript:
    image: ndtnfhomework004migratetotypescript
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 27017:27017
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/app.js"]
