version: '3.4'

services:
  ndtnfhomework004migratetotypescript:
    image: ndtnfhomework004migratetotypescript
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 27017:27017
